# Generated by Django 3.2.5 on 2021-07-03 18:04

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestingModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.base.models.gen_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("value", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
